Add error checking in String::New function
nodejs/node-addon-api pull request #1015
Opened 2021-06-28 01:40 UTC by JckXia

Added an if statement to String::New(env, const char * str) to make sure that str pointer is not null

2021-06-28 01:57 UTC, JckXia commented
Should I also add this if statement to the other` String::New `overloads that accept a C char pointer? Also  for the overload `String::New(env, const char *, length)`, it doesn't seem like there are any checks in place to make sure that the length param is indeed the length of the string passed in. If I pass a value that exceeds the length of the string ( in this case String::New(env, "abcde",46)), I get this result: 

![stringLengthCheck](https://user-images.githubusercontent.com/32422811/123567761-e6a88b80-d790-11eb-9ec5-9454627bf008.PNG)
Is this expected behavior? Thank you! 
To reproduce the above result, I defined a C++ function returning String::New(env, "abcde",46). From the JS side, I printed out the return value of this Cpp function using `console.log()`

2021-06-28 19:14 UTC, KevinEady requested changes

2021-06-28 19:14 UTC, KevinEady commented on test/name.js
> +  }
You can use `assert.throws()`

2021-06-28 19:14 UTC, KevinEady commented on napi-inl.h
> +        TypeError::New(env, "String::New recieved a nullpointer as a value"),
typo 😉

2021-07-09 13:04 UTC, KevinEady approved these changes
LGTM

2021-07-09 15:46 UTC, mhdawson approved these changes
LGTM

2021-07-09 15:51 UTC, mhdawson commented
Landed in da50b51398789185ab63ece534890f131703ffbb

2021-07-09 15:51 UTC, closed without merging